Repository halo-sigs/plugin-katex, pull requests merged in 2023-07, with the labels that each got.

#1 feat: support adding katex scripts to the post content
  .github/workflows/workflow.yaml
  .gitignore
  README.md
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/assets/logo.svg
  console/src/index.ts
  console/src/views/HomeView.vue
  console/vite.config.ts
  settings.gradle
  src/main/java/run/halo/katex/DefaultPostContentHandler.java
  src/main/java/run/halo/katex/DefaultSinglePageContentHandler.java
  src/main/java/run/halo/katex/KatexPlugin.java
  src/main/java/run/halo/starter/StarterPlugin.java
  src/main/resources/extensions/extensions.yaml
  src/main/resources/extensions/reverseProxy.yaml
  src/main/resources/logo.png
  src/main/resources/plugin.yaml
Labels: release-note-none

#3 feat: editor katext extension
  console/package.json
  console/pnpm-lock.yaml
  console/src/editor/katex/KatexRender.vue
  console/src/editor/katex/index.ts
  console/src/index.ts
Labels: release-note

#4 docs: refine readme
  README.md
Labels: release-note-none, kind/documentation

#7 chore: add halo app store release step
  .github/workflows/workflow.yaml
Labels: release-note-none, approved, lgtm, kind/improvement
